name: Release to PyPI

"on":
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-python@v4.3.0
      - run: python -m pip install -U pip setuptools build
      - run: python -m build
      - name: Publish
        uses: pypa/gh-action-pypi-publish@v1.5.1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
